

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import org.jivesoftware.smack.XMPPException;
import xmpp.PubSubClient;

/**
 *
 * @author denjae
 */
public class AdminWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public AdminWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelKonsole = new javax.swing.JLabel();
        jLabelTor = new javax.swing.JLabel();
        jComboBoxMannschaften1 = new javax.swing.JComboBox();
        jTextFieldSchuetze = new javax.swing.JTextField();
        jTextMinute = new javax.swing.JTextField();
        jTextErgebnis = new javax.swing.JTextField();
        jToggleAbsenden1 = new javax.swing.JToggleButton();
        jLabelKommentar = new javax.swing.JLabel();
        jComboBoxMannschaften2 = new javax.swing.JComboBox();
        jTextFieldKommentar = new javax.swing.JTextField();
        jTextMinute2 = new javax.swing.JTextField();
        jToggleButtonAbsenden2 = new javax.swing.JToggleButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelKonsole.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelKonsole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKonsole.setText("Publisher-Konsole");

        jLabelTor.setText("Tor hinzufuegen");

        jComboBoxMannschaften1.setMaximumRowCount(18);
        jComboBoxMannschaften1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1899 Hoffenheim", "1.FC Nuernberg", "1.FSV Mainz 05", "Bayer 04 Leverkusen", "Borussia Dortmund", "Borussia Moenchengladbach", "Eintracht Frankfurt", "FC Augsburg", "FC Bayern Muenchen", "FC Schalke 04", "Fortuna Duesseldorf", "Hamburger SV", "Hannover 96", "Sportclub Freiburg", "SpVgg Greuther Feurth", "SV Werder Bremen", "VFB Stuttgart", "VFL Wolfsburg" }));

        jTextFieldSchuetze.setText("Torschuetze");
        jTextFieldSchuetze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSchuetzeActionPerformed(evt);
            }
        });

        jTextMinute.setText("Minute");
        jTextMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMinuteActionPerformed(evt);
            }
        });

        jTextErgebnis.setText("Ergebnis");
        jTextErgebnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextErgebnisActionPerformed(evt);
            }
        });

        jToggleAbsenden1.setText("Absenden");
        jToggleAbsenden1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jToggleAbsenden1ActionPerformed(evt);
                } catch (XMPPException e) {
                    e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                }
            }
        });

        jLabelKommentar.setText("Kommentar hinzufuegen");

        jComboBoxMannschaften2.setMaximumRowCount(18);
        jComboBoxMannschaften2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1899 Hoffenheim", "1.FC Nuernberg", "1.FSV Mainz 05", "Bayer 04 Leverkusen", "Borussia Dortmund", "Borussia Moenchengladbach", "Eintracht Frankfurt", "FC Augsburg", "FC Bayern Muenchen", "FC Schalke 04", "Fortuna Duesseldorf", "Hamburger SV", "Hannover 96", "Sportclub Freiburg", "SpVgg Greuther Feurth", "SV Werder Bremen", "VFB Stuttgart", "VFL Wolfsburg" }));
        jComboBoxMannschaften2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMannschaften2ActionPerformed(evt);
            }
        });

        jTextFieldKommentar.setText("Kommentar");

        jTextMinute2.setText("Minute");
        jTextMinute2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMinute2ActionPerformed(evt);
            }
        });

        jToggleButtonAbsenden2.setText("Absenden");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabelKonsole, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabelTor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabelKommentar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                        .add(jComboBoxMannschaften2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(18, 18, 18)
                                                        .add(jTextFieldKommentar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(jTextMinute2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .add(jToggleButtonAbsenden2))
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                        .add(jComboBoxMannschaften1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(18, 18, 18)
                                                        .add(jTextFieldSchuetze, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(jTextMinute, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(jTextErgebnis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(jToggleAbsenden1))))
                                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(jLabelKonsole, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabelTor)
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jComboBoxMannschaften1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jTextFieldSchuetze, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jTextMinute, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jTextErgebnis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jToggleAbsenden1))
                                .add(18, 18, 18)
                                .add(jLabelKommentar)
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jComboBoxMannschaften2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jTextFieldKommentar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jTextMinute2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jToggleButtonAbsenden2))
                                .add(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jTextMinuteActionPerformed(java.awt.event.ActionEvent evt) {
        int min = Integer.parseInt(jTextMinute.getText());
    }

    private void jTextErgebnisActionPerformed(java.awt.event.ActionEvent evt) {
        String ergebnis = jTextErgebnis.getText();

    }

    private void jTextMinute2ActionPerformed(java.awt.event.ActionEvent evt) {
        int min = Integer.parseInt(jTextMinute.getText());
    }

    private void jComboBoxMannschaften2ActionPerformed(java.awt.event.ActionEvent evt) {
        String team = jComboBoxMannschaften2.getName();
    }

    private void jToggleAbsenden1ActionPerformed(java.awt.event.ActionEvent evt) throws XMPPException {
        pubsub.pubGoal(team, schuetze, min, ergebnis);
    }

    private void jTextFieldSchuetzeActionPerformed(java.awt.event.ActionEvent evt) {
        schuetze = jTextFieldSchuetze.getText();
    }

    void setPubSub(PubSubClient pubsub){

        this.pubsub=pubsub;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JComboBox jComboBoxMannschaften1;
    private javax.swing.JComboBox jComboBoxMannschaften2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelKommentar;
    private javax.swing.JLabel jLabelKonsole;
    private javax.swing.JLabel jLabelTor;
    private javax.swing.JTextField jTextErgebnis;
    private javax.swing.JTextField jTextFieldKommentar;
    private javax.swing.JTextField jTextFieldSchuetze;
    private javax.swing.JTextField jTextMinute;
    private javax.swing.JTextField jTextMinute2;
    private javax.swing.JToggleButton jToggleAbsenden1;
    private javax.swing.JToggleButton jToggleButtonAbsenden2;

    int min;
    String ergebnis;
    String team;
    String schuetze;
    PubSubClient pubsub;

}
